import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import React from "react";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Plataforma de Editores de Video</title>
        <meta name="description" content="Generated by EditVid" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Conheça o <a href="">VidEdit!</a>
        </h1>

        <p className={styles.description}>
          Uma plataforma para encontrar Editores de Vídeos para seu canal{" "}
          <code className={styles.code}></code>
        </p>
        <div className={styles.card}>
          <div className={styles.grid}>
            <Link href="/cadastro" className={styles.card}>
              <a>Cadastro &rarr;</a>
            </Link>
          </div>
        </div>
        <div className={styles.card}>
          <div className={styles.grid}>
            <Link href="/quemsomos" className={styles.card}>
              <a>Quem Somos &rarr;</a>
            </Link>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image
              src="/horizontal_on_white_by_logaster.png"
              alt="VidEdit Logo"
              width={72}
              height={16}
            />
          </span>
        </a>
      </footer>
    </div>
  );
}
